#!/usr/bin/env python3
"""
embed_icons.py — Convert assets/icons/*.svg to src/dashboard_icons.[h|c]

Each SVG is stored as a uint8_t array and wrapped in an lv_image_dsc_t so
LVGL's built-in SVG decoder can render it at runtime.  No ThorVG required.

Run from the repo root:
    python tools/embed_icons.py
"""

import os
import re
import sys

ICONS_DIR   = os.path.join("assets", "icons")
OUT_H       = os.path.join("src",    "dashboard_icons.h")
OUT_C       = os.path.join("src",    "dashboard_icons.c")

LV_IMAGE_HEADER_MAGIC = 0x19
LV_COLOR_FORMAT_RAW   = 0x01
ICON_W = 24
ICON_H = 24

HEADER_GUARD = "DASHBOARD_ICONS_H"


def svg_to_c_name(filename: str) -> str:
    """
    'cloud--weather.svg' -> 'ICON_CLOUD_WEATHER'
    'music-2--entertainment.svg' -> 'ICON_MUSIC_2_ENTERTAINMENT'
    """
    stem = os.path.splitext(filename)[0]
    stem = stem.replace("--", "_")
    stem = stem.replace("-", "_")
    return "ICON_" + stem.upper()


def array_name(sym: str) -> str:
    return "_" + sym.lower() + "_data"


def to_hex_rows(data: bytes, cols: int = 12) -> str:
    """Format bytes as hex with `cols` values per line, indented 4 spaces."""
    rows = []
    for i in range(0, len(data), cols):
        chunk = data[i:i + cols]
        rows.append("    " + ", ".join(f"0x{b:02x}" for b in chunk))
    return ",\n".join(rows)


def collect_icons(icons_dir: str):
    entries = []
    if not os.path.isdir(icons_dir):
        sys.exit(f"ERROR: icons directory not found: {icons_dir}")
    for fname in sorted(os.listdir(icons_dir)):
        if not fname.endswith(".svg"):
            continue
        path = os.path.join(icons_dir, fname)
        with open(path, "rb") as f:
            data = f.read()
        sym   = svg_to_c_name(fname)
        arr   = array_name(sym)
        entries.append((fname, sym, arr, data))
    return entries


def write_header(entries, path):
    lines = [
        f"#ifndef {HEADER_GUARD}",
        f"#define {HEADER_GUARD}",
        "",
        "#include \"lvgl.h\"",
        "",
        "/* Auto-generated by tools/embed_icons.py — do not edit by hand. */",
        "",
    ]
    for _, sym, _, _ in entries:
        lines.append(f"extern const lv_image_dsc_t {sym};")
    lines += ["", f"#endif /* {HEADER_GUARD} */", ""]
    with open(path, "w", newline="\n") as f:
        f.write("\n".join(lines))


def write_source(entries, path):
    lines = [
        "#include \"dashboard_icons.h\"",
        "",
        "/* Auto-generated by tools/embed_icons.py — do not edit by hand. */",
        "",
    ]
    for fname, sym, arr, data in entries:
        lines.append(f"/* {fname} */")
        lines.append(f"static const uint8_t {arr}[] = {{")
        lines.append(to_hex_rows(data))
        lines.append("};")
        lines.append(f"const lv_image_dsc_t {sym} = {{")
        lines.append(f"    .header = {{")
        lines.append(f"        .magic = 0x{LV_IMAGE_HEADER_MAGIC:02x},")
        lines.append(f"        .cf    = 0x{LV_COLOR_FORMAT_RAW:02x},")
        lines.append(f"        .w     = {ICON_W},")
        lines.append(f"        .h     = {ICON_H},")
        lines.append(f"    }},")
        lines.append(f"    .data_size = sizeof({arr}),")
        lines.append(f"    .data      = {arr},")
        lines.append("};")
        lines.append("")
    with open(path, "w", newline="\n") as f:
        f.write("\n".join(lines))


def main():
    entries = collect_icons(ICONS_DIR)
    if not entries:
        sys.exit(f"ERROR: no .svg files found in {ICONS_DIR}")
    print(f"Found {len(entries)} icon(s).")
    write_header(entries, OUT_H)
    print(f"Written: {OUT_H}")
    write_source(entries, OUT_C)
    print(f"Written: {OUT_C}")


if __name__ == "__main__":
    main()
