#ifndef DASHBOARD_ICONS_H
#define DASHBOARD_ICONS_H

#include "lvgl.h"

/* Auto-generated by tools/embed_icons.py — do not edit by hand. */

extern const lv_image_dsc_t ICON_CALENDAR_DATE;
extern const lv_image_dsc_t ICON_CHEVRON_LEFT_NAV;
extern const lv_image_dsc_t ICON_CHEVRON_RIGHT_NAV;
extern const lv_image_dsc_t ICON_CLOCK_TIME;
extern const lv_image_dsc_t ICON_CLOUD_WEATHER;
extern const lv_image_dsc_t ICON_CLOUD_FOG_FOG;
extern const lv_image_dsc_t ICON_CLOUD_HAIL_HAIL;
extern const lv_image_dsc_t ICON_CLOUD_RAIN_RAIN;
extern const lv_image_dsc_t ICON_CLOUD_SUN_PARTLYCLOUDY;
extern const lv_image_dsc_t ICON_FLOWER_HIGH_POLLEN;
extern const lv_image_dsc_t ICON_LEAF_POLLEN;
extern const lv_image_dsc_t ICON_LIGHTBULB_LIGHTING;
extern const lv_image_dsc_t ICON_MUSIC_2_ENTERTAINMENT;
extern const lv_image_dsc_t ICON_PAUSE_TRANSPORT_PAUSE;
extern const lv_image_dsc_t ICON_PENCIL_EDIT;
extern const lv_image_dsc_t ICON_PLAY_TRANSPORT_PLAY;
extern const lv_image_dsc_t ICON_PLUS_ADD;
extern const lv_image_dsc_t ICON_REFRESH_CW_RESTART;
extern const lv_image_dsc_t ICON_REPEAT_2_RECUR;
extern const lv_image_dsc_t ICON_SETTINGS_2_CONFIG;
extern const lv_image_dsc_t ICON_SKIP_BACK_TRANSPORT_PREV;
extern const lv_image_dsc_t ICON_SKIP_FORWARD_TRANSPORT_NEXT;
extern const lv_image_dsc_t ICON_SNOWFLAKE_SNOW;
extern const lv_image_dsc_t ICON_SUN_UV;
extern const lv_image_dsc_t ICON_THERMOMETER_COLD_DROP;
extern const lv_image_dsc_t ICON_THERMOMETER_HEATING;
extern const lv_image_dsc_t ICON_TRASH_2_DELETE;
extern const lv_image_dsc_t ICON_UMBRELLA_RAIN;
extern const lv_image_dsc_t ICON_VOLUME_2_VOLUME;
extern const lv_image_dsc_t ICON_WIND_WINDY;
extern const lv_image_dsc_t ICON_X_DISMISS;
extern const lv_image_dsc_t ICON_ZAP_POWER;

#endif /* DASHBOARD_ICONS_H */
